### ISSUE TITLE
A small issue with the templates

### ISSUE THREAD

**Issue by omrihar** [bramses/bramses-highly-opinionated-vault-2023#5]
Hi Bramses,

thanks for sharing this great vault! I stumbled upon it during my searches and I really like what you did with it. 
When looking through some of the templates it seems that you lost some of the templater code, especially in the yaml frontmatter. e.g. in `Templates/People.md` it seems that all the titles are simply "People"? 
And in `Templates/Zettelkasten Note.md` are all the titles Lorem Ipsum?

Anyways, thanks for the good work! I'll definitely borrow liberally for my own system ;)

**Comment by bramses** [comment]
Hi @omrihar, thanks for reaching out!

> Templates/People.md it seems that all the titles are simply "People"? And in Templates/Zettelkasten Note.md are all the titles Lorem Ipsum?

When you lint a file (ctrl/cmd + s by default in BHOV) it should automatically replace the `Lorem Ipsum` with the first H1 in the file! :)

**Comment by bramses** [comment]
You can also trigger it manually in the Command Palette by running `Linter: Lint the current File`
